spring.application.name=book-lib

spring.flyway.enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/book-lib-2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:book-lib}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:book123}

spring.flyway.url=${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5435/book-lib-2}
spring.flyway.user=${SPRING_FLYWAY_USERNAME:book-lib}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD:book123}
spring.datasource.driverClassName=org.postgresql.Driver

jwt.secret=${JWT_SECRET:a3f8c2e1d7b94f6a2e5c8d1f4b7e9a3c6f2d5e8b1c4a7f0e3d6b9c2f5a8e1d4}

user.staff.username=staff
user.staff.password=staff123

global.configuration.max-loan=${GLOBAL_CONFIGURATION_MAX_LOAN:1}
global.configuration.allow-member-to-borrow-when-overdue-loan=${GLOBAL_CONFIGURATION_ALLOW_MEMBER_TO_BORROW_WHEN_OVERDUE_LOAN:false}
global.configuration.loan-due-days=${GLOBAL_CONFIGURATION_LOAN_DUE_DAYS:7}