spring.application.name=book-lib

# since I use postgresql 15.4 in my local, flyway version does not support with this version of flyway core lib
spring.flyway.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5435/book-lib
spring.datasource.username=book-lib
spring.datasource.password=book123
spring.datasource.driverClassName=org.postgresql.Driver

user.guest.username=guest
user.guest.password=guest123

global.configuration.max-loan=1
global.configuration.allow-borrow-with-overdue-loan=false
global.configuration.max-loan-duration=7